version: '3.3'

services:
  traefik:
    image: traefik:v1.4.2-alpine
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=81
        - traefik.frontend.rule=Host:traefik.services.alin.be
        - traefik.frontend.entryPoints=https,http
        - traefik.docker.network=traefik-net
    ports:
# it's a RP, everithing is on :80 or :443
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/etc/traefik/acme/acme.json
      - ./keys/:/etc/traefik/keys/
      - ./log/traefik.log:/etc/traefik/log/traefik.log
      - ./log/access.log:/etc/traefik/log/access.log
      - ./localtime:/etc/localtime

networks:
  default:
    external:
      name: traefik-net 
