version: '3'

services:
  traefik:
    image: traefik:v1.2.3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
# Admin 81
      - "81:81"
    volumes:
# Automatic discover docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/etc/traefik/acme/acme.json
      - ./keys/:/etc/traefik/keys/
    labels:
      - traefik.port=81
      - traefik.frontend.rule=Host:traefik.services.alin.be
      - traefik.frontend.entryPoints=https,http
    networks:
      - webgateway
      - web

networks:
  webgateway:
    driver: bridge
  web:
    external:
      name: traefik_webgateway
