version: '3.2'

services:
  traefik:
    image: traefik:v1.3.3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
# Admin 81
      - "81:81"
    volumes:
# Automatic discover docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/etc/traefik/acme/acme.json
      - ./keys/:/etc/traefik/keys/
      - ./log/traefik.log:/etc/traefik/log/traefik.log
      - ./log/access.log:/etc/traefik/log/access.log
    labels:
      - traefik.port=81
      - traefik.frontend.rule=Host:traefik.services.alin.be
      - traefik.frontend.entryPoints=https,http
    networks:
      - webgateway
      - web
 
networks:
  webgateway:
    driver: bridge
  web:
    external:
      name: traefik_webgateway
