################################################################
# Global Configuration - Main Section
################################################################

debug = true
InsecureSkipVerify = true

################################################################
# Global Configuration - Log Section
################################################################

#logLevel = "ERROR"
logLevel = "INFO"
[traefiklog]
filepath = "/etc/traefik/log/traefik.log"

[accessLog]
filePath = "/etc/traefik/log/access.log"

################################################################
# Entry Points Definition
################################################################

defautEntryPoints= ["http","https","ws","wss"] 
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
      [entryPoints.https.tls]
  [entryPoints.traefik]
  address = ":81"
    [entryPoints.traefik.auth]
     [entryPoints.traefik.auth.basic]
       users = [ "admin:$apr1$x6DlzZ7s$v6vd2UbSO/bhoSIHnYE4D1" ]

################################################################
# ACME (Let's Encrypt) configuration
################################################################
[acme]
email= "patrickalin@gmail.com"
storage= "/etc/traefik/acme/acme.json"
acmeLogging= true
onHostRule = true
entryPoint = "https"
[acme.httpChallenge]
  entryPoint = "http"

################################################################
# Web Backend
################################################################
[api]

[ping]

[metrics]

################################################################
# Docker configuration backend
################################################################
[docker]
domain = "services.alin.be"
docker = true
swarmmode = true

[file]
[frontends]
    [frontends.synology]
    backend = "synology"
    entrypoints = ["http", "https"]
    passHostHeader = true
        [frontends.synology.routes.syno]
        rule = "Host:synology.services.alin.be"

[backends]
    [backends.synology]
      [backends.synology.servers.server1]
        url = "https://192.168.10.10:1111"
